# Generated by Django 5.2 on 2025-04-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_signup_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='enrollment_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
