# Generated by Django 5.2 on 2025-04-30 07:03

import django.db.models.deletion
import django.utils.timezone
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_signup_enrollment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Asia/Kolkata'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_present', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.signup')),
            ],
        ),
    ]
